### PR TITLE
Enable installation of web components through bower

### PR DESCRIPTION
**Pull request by cabello**
I decided to make this a tiny PR, because others can take advantage of that while I am doing the bounty 14.

Now you can for example, run: `bower install jquery` and refer it in your templates.

### CODE REVIEW

**Comment by colevscode** [comment]
kinda mixed feelings about this. The project is so small, do you anticipate that we'll have more than just jquery, maybe a plugin or two, and a dependency?

**Comment by fiatjaf** [comment]
What Javascript libraries are you using, @cabello? A lot of them?

Adding Bower dependency management is a difficult thing, many people may not like it, and may prefer a NPMish approach or other, we should discuss (or let @colevscode decide), but I think it is the best to postpone these discussions for when we really need them.

**Comment by cabello** [comment]
We can do the old style, using bower would be like using requirement.txt we would not have these libs in the repo, and they would be installed on demand, it would also make it easy to install new libraries.

I am not using many libraries just yet, for now I am planning to use bootstrap/jquery or foundation/jquery, I don't know everyones preference.

**Comment by cabello** [comment]
I just added a `bower.json` to the PR, I left authors empty for now because I am not sure if you guys want to be listed there (with or without e-mails).

**Comment by cabello** [comment]
> Adding Bower dependency management is a difficult thing, many people may not like it

I am not sure why, even though I program mainly with Python and basic Javascript on daily basis I have `npm`, `pip`, `gem`, `bower`, `composer.phar` all installed on my machine. In general is a good idea to use a package manager, if the package manager simplify your developer life.

**Comment by colevscode** [comment]
I don't have anything against using bower. But my feeling is that this app
will be using only a few js libraries. I'd prefer to wait to see how
complex our front end code gets. For now lets just keep minified copies in
a static/js folder.

**Comment by cabello** [comment]
Okay, I am closing it for now.

**Pull request closed without merging**
