### PR TITLE
Redis adapter to help simplify the tests

### PR DESCRIPTION
**Pull request by cabello**

### CODE REVIEW

**Comment by colevscode** [comment]
Thanks! However I'm not sure how this is an improvement. It just replaces the get_redis function with different logic which is similarly overridden in the test setUpClass (and not cleaned up).

I liked your suggestion to use the mock library, and remove the singleton thing.

**Comment by cabello** [comment]
I was doing some research before trying to remove the singleton, I just read [here](http://flask.pocoo.org/snippets/71/) the following:
> A redis instance is thread safe so you can just keep this on the global level and use it directly.

Do you think there is any advantage of lazily instantiating redis?

---

Then the next step will be to use the mock library, but instead of mocking the way I previously mentioned, we can try to do something similar to Django [`override_settings`](https://docs.djangoproject.com/en/1.7/topics/testing/tools/#django.test.override_settings) decorator.

**Comment by fiatjaf** [comment]
I don't understand what we are gaining with these string parsers. I also don't think we are going to gain too much from using Mock. In fact when I was writing the tests with Redis I tried to use Mock with https://github.com/locationlabs/mockredis, but it was too painful for such a simple job that `fakeredis` did so well.

In the end we will end up having a global REDIS object and that is fine. Mocking seems to me like a dirty hack around that, not a beautiful and clean solution.

**Comment by cabello** [comment]
Yeah... maybe you are right, your gain in flexibility is desirable in a multi-purpose project like Django, but questionable since this is a very specific project, I would personally do two things:
app.py:
```
redis = redis.StrictRedis.from_url(settings.REDIS_URL)
```

And in tests replace redis by fake redis.

I think this is the simpler approach, I overly complicated things because I wanted to remove the getter `get_redis` while keeping the possibility of replacing the library by something else.

**Comment by colevscode** [comment]
The only reason I lazily instantiated redis was so that I'd have a chance to replace it in the test setup. Otherwise, by the time we setup the test, the global strictRedis object has already been imported throughout the app. The alternative is to patch it after the fact with something like mock.

Note that this isn't a problem with the test sql database, because that database connection isn't established until create_app(), so we have the opportunity to override it in the test setup before creating the app.

I don't like the REDIS() singleton pattern, and would like to remove it in favor of the standard global REDIS instance, if possible. The only solution that I know of for this is to use mock, or some other monkeypatch library.

**Comment by fiatjaf** [comment]
Maybe the solution is to use a variant of https://github.com/rhyselsmore/flask-redis, then.
It will only connect to the redis URL when we call `init_app`, so it will work, just like SQLAlchemy does.

We only need to change the code to make it recognize a false `REDIS_URL` (maybe `redis:fake` or anything) for when we are testing, and instantiate a `fakeredis` instance instead of a `redis` instance.

Also, we need to use `redis.StrictRedis`, not `redis.Redis`.

**Comment by cabello** [comment]
That sounds like a plan, in order to use flask-redis all you need to do in the tests is to patch the `RedisClass` import with something like:
```with patch.object('flask_redis.RedisClass') ...`

If you don't wanna use `with` there are other ways to do that on `setUp` and `tearDown` that achieve the same result.

By the time you import the project, run the tests and therefore call `Redis.init_app` the `RedisClass` will be the fake redis one.

**Comment by fiatjaf** [comment]
Well, we can't use the library the way it is, we must change it to use `StrictRedis` (or we can use [this simple patch](https://github.com/grivescorbett/flask-redis/commit/b1d06463f0b723066e040575ee6630fee6c086c3))(in fact, we can also change the formspree code to use `Redis` instead of `StrictRedis`).

So, we can use Mock and patch, but I still think these things are dangerous, mainly because they are too "magical", some distracted developer could mess up things in the future (I'm speaking for myself). I suggest that instead we modify this flask-redis library and add fakeredis to it, instantiating fakeredis instead of redis whenever is approppriate (we would just signal that with a manual settings change, like [we do with the SQLALCHEMY_DATABASE_URI](https://github.com/asm-products/formspree/blob/4a45a3bd2347a8eadd894cafb2e6d76965d8d805/tests/formspree_test_case.py#L19)).

**Comment by colevscode** [comment]
I wouldn't be afraid of mocks / monkey patching. It's pretty standard for testing to use those tools, and we will only be using them in the testing library, not in our production code. The advantage is that our production code can be totally free of test logic, which is a good thing.

**Comment by colevscode** [comment]
I like the idea of using flask-redis, it addresses the redis inception problem. I don't really like the idea of changing the flask-redis code though, since then we'll be maintaining a fork of that dependency. Before we change that extension we should look at our code and see where we rely on StrictRedis. I think the differences are mostly superficial, like different function names for a few things. It should be easy to switch to regular redis, especially since we only use it for form counts.

**Comment by fiatjaf** [comment]
In fact we only have to change the order of the parameters of `redis.expire`.

**Comment by fiatjaf** [comment]
Nevermind, we don't need to change anything.

**Comment by colevscode** [comment]
@cabello do you want to make the changes suggested above and resubmit? I think the summary is:

- remove the string adapter stuff
- remove the whole REDIS() singleton 
- swap in flask-redis so that initialization of the global redis object is deferred until init_app
- use mock to replace the redis object in the FormspreeTestCase setUp() method

**Comment by cabello** [comment]
Yes, I will try to make these changes and resubmit.

**Comment by cabello** [comment]
@colevscode Just squashed everything in a single commit, check it out please.

**Pull request merged**
